server:
  port: 8083
spring:
  application:
    name: oauth2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://114.115.140.198/postgres?currentSchema=jwt
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5 # ??????????10???0???maximum-pool-size??????maximum-pool-size
      maximum-pool-size: 10 # ??????????0????????10??????1?????minimum-idle??
      idle-timeout: 30000 # ????????????600000?10????????max-lifetime?max-lifetime>0??????0????0???10???????10??
      max-lifetime: 540000 # ????????????0???30??????????30??.?????mysql????????
      connection-timeout: 30000 # ????????????250????????????30?
      connection-test-query: SELECT 1 # ???????????????
      pool-name: hikari1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://123.249.70.126:7001/keycloak/auth/realms/SpringBootKeycloak
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

